version: "3.8"
services:
  drone:
    image: drone/drone:latest
    container_name: drone-ci
    ports:
      - 81:80
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: always
    environment:
      - DRONE_AGENTS_ENABLED=true
      - DRONE_GITEA_CLIENT_ID=
      - DRONE_GITEA_CLIENT_SECRET=
      - DRONE_GITEA_SERVER=https://git.domain.tld
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_TLS_AUTOCERT=false
      - DRONE_SERVER_HOST=drone.domain.tld
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET= # openssl rand -hex 16
      - DRONE_LOGS_DEBUG=false
      - DRONE_ADMIN=your_user_name
      - DRONE_USER_CREATE=username:your_user_name,admin:true
  drone-runner-docker:
    container_name: drone-ci-runner-docker
    image: drone/drone-runner-docker:latest
    restart: always
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - drone
    environment:
      - DRONE_RPC_HOST=drone.domain.tld
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET= # use the same as above
      - DRONE_RUNNER_NAME=drone-runner-docker