version: '3.7'

services:
  polr:
    image: ajanvier/polr
    container_name: polr
    ports:
      - "80:8080"
    environment:
      # Database
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=polr
      - DB_USERNAME=polr
      - DB_PASSWORD=
      - DB_ROOT_PASSWORD=
      # Admin
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=
      - ADMIN_EMAIL=email@example.com
      # Configs
      - APP_NAME=domain.tld
      - APP_PROTOCOL=https://
      - APP_ADDRESS=domain.tld
      #
      - POLR_ALLOW_ACCT_CREATION=false
      - POLR_ACCT_ACTIVATION=true
      - POLR_ACCT_CREATION_RECAPTCHA=false
      - POLR_RECAPTCHA_SITE_KEY=
      - POLR_RECAPTCHA_SECRET=
      - POLR_BASE=62
      #
      - SETTING_PUBLIC_INTERFACE=false
      - SETTING_SHORTEN_PERMISSION=true
      - SETTING_INDEX_REDIRECT=/login
      - SETTING_REDIRECT_404=/
      - SETTING_PASSWORD_RECOV=true
      - SETTING_AUTO_API=false
      - SETTING_ANON_API=
      - SETTING_ANON_API_QUOTA=
      - SETTING_PSEUDORANDOM_ENDING=true
      - SETTING_ADV_ANALYTICS=false
      - SETTING_RESTRICT_EMAIL_DOMAIN=true
      - SETTING_ALLOWED_EMAIL_DOMAINS=domain.tld
      # mail
      - MAIL_HOST=
      - MAIL_PORT=1025
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - MAIL_FROM_ADDRESS=
      - MAIL_FROM_NAME=Polr
    depends_on:
        - mariadb
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=polr
      - MYSQL_USER=polr
      - MYSQL_PASSWORD=
    volumes:
      - /var/lib/mysql