version: "3.8"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    user: 1001:1001
    environment:
      - FB_DATABASE=/database.db
      - FB_ROOT=/files
      - FB_LOG=stdout
      - FB_PORT=80
      - FB_USERNAME=
    ports:
      - 80:80
    volumes:
      - data:/files
      - /root/docker/filebrowser/database.db:/database.db
      - /root/docker/filebrowser/theme:/theme
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
volumes:
  data:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=lando.local,hard,rw,nfsvers=4"
      device: ":/mnt/user/docker/filebrowser"