# This is an example drone docker pipeline that builds a static website using jekyll
#   and deploys it to a staging website for testing before pusing to production

kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: restore-cache
  image: drillster/drone-volume-cache
  volumes:
  - name: cache
    path: /cache
  settings:
    restore: true
    mount:
    - vendor
  ttl: 7

- name: build
  image: ruby:3.0
  commands:
    - "echo \"url: 'staging.domain.tld'\" > ./_config_dev.yml"
    - "echo \"baseurl: '/${DRONE_REPO}'\" >> ./_config_dev.yml"
    - "echo \"title: '${DRONE_REPO}'\" >> ./_config_dev.yml"
    - bundle config set --local deployment 'true'
    - bundle install
    - JEKYLL_ENV=development bundle exec jekyll build --verbose --config _config.yml,_config_dev.yml

- name: rebuild-cache
  image: drillster/drone-volume-cache 
  volumes:
  - name: cache
    path: /cache
  settings:
    rebuild: true
    mount:
    - vendor

- name: stage
  image: appleboy/drone-scp
  settings:
    host: ssh.staging.domain.tld
    username: 
      from_secret: staging_username
    password: 
      from_secret: staging_password
    port: 22
    target: /var/www/html/${DRONE_REPO}/
    source: _site
    strip_components: 1
    overwrite: true

trigger:
  branch:
  - main

volumes:
- name: cache
  host:
    path: /var/lib/drone/temp

branches: main

---
kind: pipeline
type: docker
name: deploy
steps:
- name: deploy
  image: plugins/webhook
  settings:
    urls: https://git.domain.tld/api/v1/repos/${DRONE_REPO}/mirror-sync
    method: POST
    content_type: application/json
    headers:
      from_secret: gitea_token
trigger:
  event:
  - promote
  target:
  - production
branches: main